### ISSUE TITLE
Popularizing the Mod

### ISSUE THREAD

**Issue by Rogenar** [JDDev0/EnergizedPower#1]
Does Energizedpower mod come out for fabric version?

**Comment by JDDev0** [comment]
Energized Power is now available for Fabric!
At the moment only 1.19.3 is supported, backports for older versions (1.19.2, 1.18.2, and 1.17.1) will be released soon.

**Comment by Rogenar** [comment]
this is great. I'm downloading the mod now. If I encounter an error, I'll let you know. In the meantime, we need to popularize this mod. so we can share on aternos server.

**Comment by JDDev0** [comment]
In what way should we popularize this mod?

**Comment by Rogenar** [comment]
as youtube video content. It could be a mod trailer.
