### ISSUE TITLE
Slow fuel check on Fabric

### ISSUE THREAD

**Issue by Technici4n** [JDDev0/EnergizedPower#10]
Hello, I randomly found this line: https://github.com/JDDev0/EnergizedPower/blob/3cb8d95dec16519a58d6e28c8b272123e9309ff1/src/main/java/me/jddev0/ep/block/entity/CoalEngineBlockEntity.java#L68.

Creating the full map can be extremely slow in large mod packs, I would recommend using `FuelRegistry.INSTANCE.get(item) != null` instead.

**Comment by JDDev0** [comment]
Thanks for bringing this up! I will fix it in v1.6.1.
