### ISSUE TITLE
Recipes Not Showing in REI

### ISSUE THREAD

**Issue by DinnerBeef** [JDDev0/EnergizedPower#11]
https://s.dinnerbeef.com/gOXe5/zUniKuSa81.png/raw

https://s.dinnerbeef.com/gOXe5/REgIgezU76.txt

None of the mods recipes are showing in REI 
Mod Version: energizedpower-1.20.4-1.7.1.jar
Minecraft Version: 1.20
Forge Version: 46.0.14

**Comment by JDDev0** [comment]
I will fix it in v1.7.3.
This will most likely be the **last** update for **1.20**, because **1.20.1** is already available.

**Comment by JDDev0** [comment]
I have already released the fix for 1.20 and 1.20.1 (*1.20.1 is not yet approved on CurseForge*).
