### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Roby1164** [JDDev0/EnergizedPower#12]
I would like to add the Italian translation.
I attach here the file, tested and working.
Only missing link for credits.
[it_it.zip](https://github.com/JDDev0/EnergizedPower/files/11779850/it_it.zip)

**Comment by JDDev0** [comment]
Thank you for your contribution!

I will release it in v1.7.5!

**Comment by JDDev0** [comment]
There are some text overflow problems in the Energized Power Book. But I will fix them by making the book pages larger.

**Comment by Roby1164** [comment]
👍
