### ISSUE TITLE
Charger does not accept Copper Ingots

### ISSUE THREAD

**Issue by Roby1164** [JDDev0/EnergizedPower#14]
I have a problem, I can't energize the ingots. From what I understand, the charger should be used, but it accepts batteries, while it doesn't take any ingots, this prevents me from progressing.

Is this a problem or am I doing something wrong??

**Comment by Roby1164** [comment]
Nothing, ok fixed, there was also a wrong translation, which I corrected.

**Comment by JDDev0** [comment]
> I have a problem, I can't energize the ingots. From what I understand, the charger should be used, but it accepts batteries, while it doesn't take any ingots, this prevents me from progressing.

You can insert Copper with the cursor, but it will only work if there is only 1 copper ingot in the cursor.
This is a bug in the Fabric version which will be fixed in a future update.
