### ISSUE TITLE
Advancement progress disappeared

### ISSUE THREAD

**Issue by Roby1164** [JDDev0/EnergizedPower#19]
I put the latest release,1.20.1 - 2.0.0-beta-2 [FABRIC], but the progress has disappeared

**Comment by JDDev0** [comment]
Of what did the progress disappeared?

**Comment by JDDev0** [comment]
If you are referring to #18, no progress on it_it.json disappeared. 2.0.0 beta 2 was released 3 hours prior to those changes, so the updates weren't released yet. They will be released in the next beta version.

**Comment by Roby1164** [comment]
No, I'm talking about minecraft progress, until beta 1 they were still there.

**Comment by Roby1164** [comment]
These, which with the energizedpower-1.20.1-1.8.0-beta-1-fabric, were present
![Screenshot 2023-08-11 230747](https://github.com/JDDev0/EnergizedPower/assets/24955554/f44cd90e-1b1c-432b-921c-d06a1320f912)

**Comment by JDDev0** [comment]
The advancements were split into two tabs.
All advanced advancements are now in another tab therefore they have got a new id.
All basic advancements were renamed and have a new id too.

**Comment by JDDev0** [comment]
You don't need to craft those items again. It is enough if the items are in your inventory. E.g. you can break the Energizer and place it back where it was then you will get the Energizer advancement again.

**Comment by JDDev0** [comment]
To be honest I didn't thought about that when I changed split all advancements into two tabs.

**Comment by Roby1164** [comment]
Ok ok, everything works.... :D
