### ISSUE TITLE
Turkish translation of Energised Power mode

### ISSUE THREAD

**Issue by EyyupBerkOZASLAN** [JDDev0/EnergizedPower#29]
**_It's a bit late, I think! But the translation of the Energised Power Mode is finished!_**
            
             _**Translation is here!**_
               
                                   
[tur.tr.json](https://github.com/JDDev0/EnergizedPower/files/13328800/tur.tr.json)

                                    
        **I hope you like the translate!**

**Comment by JDDev0** [comment]
Thank you very much!
