### ISSUE TITLE
New Textures For Energized Copper and Gold 

### ISSUE THREAD

**Issue by flashbulbs** [JDDev0/EnergizedPower#3]
The current textures of Energized Copper and Gold are kind of rough so a texture change would be nice. I attached my own textures I made for them as well. 
![energized_copper_ingot](https://user-images.githubusercontent.com/94999662/218579047-200ff9af-9836-41da-9b3a-0d172e5c9a72.png)
![energized_gold_ingot](https://user-images.githubusercontent.com/94999662/218579048-29ed9e62-6920-46fc-aad5-201dec501b97.png)

**Comment by JDDev0** [comment]
Can I use this textures within the MIT license of the project and for the project logo?
You would be credited in the README and project descriptions.
I'd like to use this textures for the next release (v1.4.0).

**Comment by flashbulbs** [comment]
You are free to use these textures.

**Comment by JDDev0** [comment]
Thanks
