### ISSUE TITLE
Fluid Cables dont connect to cauldrons.

### ISSUE THREAD

**Issue by DerShendi** [JDDev0/EnergizedPower#33]
As the Title says the fluid cables dont connect to Cauldrons 
![image](https://github.com/JDDev0/EnergizedPower/assets/51245094/62293b2c-d51c-4ace-a22b-a6306cafad63)
I needed this for a lava farm in skyblock so thats how i found out. Im playing in the latest release in 1.20.4 in fabric (1.20.4-2.7.0-fabric)

**Comment by JDDev0** [comment]
Fluid Cauldrons on Fabric do not implement the Fluid API which is required for the pipes to function.

**Comment by JDDev0** [comment]
I will add Cauldron support to the Drain block in a future release.

**Comment by DerShendi** [comment]
Thx :)

**Comment by JDDev0** [comment]
Fluids from Cauldrons can be extracted with the Drain as of v2.8.0 on Fabric.
