### ISSUE TITLE
Energized Power Keeps Crashing My Server 

### ISSUE THREAD

**Issue by ToxicTerror86** [JDDev0/EnergizedPower#34]
[crash-2024-01-13_19.32.25-server.txt](https://github.com/JDDev0/EnergizedPower/files/13929281/crash-2024-01-13_19.32.25-server.txt)

Im not sure whats causeing this but crash report says Energized Power its causing massive lag and crashing out my server

**Comment by JDDev0** [comment]
You should place transformers to separate long cable lines or cables where many machines are connected in order to reduce lag.

**Comment by JDDev0** [comment]
In the crash report there are 229 Solar Panels, you should connect groups of 25 to a cable which connects to a transformer, afterwords you can connect all the output of those transformers to another transformer. The output of the last transformer can go to your machines.
![image](https://github.com/JDDev0/EnergizedPower/assets/37939362/6b69a95b-407a-4efc-91a9-ee31ca92c69b)

**Comment by ToxicTerror86** [comment]
oh ok thank you i was unaware of that i will let them know

**Comment by JDDev0** [comment]
FYI Energized Power cables where at least one energy producer is connect will check the whole network for energy consumers where energy is required and distributes energy evenly. In your case this is done 229 times for the whole network which is most likely very large. Transformers split the cable network into multiple parts.

**Comment by ToxicTerror86** [comment]
we had a member that had 196 panels connected to try to supply a massive kingdom he was doing
