### ISSUE TITLE
Support for modded wood types

### ISSUE THREAD

**Issue by MehanikTMYT** [JDDev0/EnergizedPower#35]
can you add support to any woods from mods as biomes of plenty, RegionsUnexplored etc?

**Comment by JDDev0** [comment]
I will add support for modded wood types in a future update or as a separate compatibility mod.

**Comment by JDDev0** [comment]
I have released two Energized Power Add-ons (One for Biomes O' Plenty and one for Region Unexplored):
- [Energized Power - Biomes O' Plenty](https://github.com/JDDev0/EnergizedPower-BiomesOPlenty)
- [Energized Power - Region Unexplored](https://github.com/JDDev0/EnergizedPower-RegionsUnexplored)
