### ISSUE TITLE
Feature Request: CCTweaked integration

### ISSUE THREAD

**Issue by anthonybrunelle** [JDDev0/EnergizedPower#39]
Computers will not interact with blocks such as tanks and batteries. Less of an issue more of a feature request.

**Comment by JDDev0** [comment]
On Fabric the Energy and Fluid generic CCTweaked APIs are missing (See [https://github.com/cc-tweaked/CC-Tweaked/issues/1822](https://github.com/cc-tweaked/CC-Tweaked/issues/1822)). I will not fix this myself, but you could try out this mod: [https://modrinth.com/mod/unlimitedperipheralworks](https://modrinth.com/mod/unlimitedperipheralworks)

**Comment by JDDev0** [comment]
But I'm currently working on EnergizedPower specific CCTweaked integrations for Redstone Mode, Comparator Mode, Time controller, and Weather controller interactions
