### ISSUE TITLE
More New Textures

### ISSUE THREAD

**Issue by flashbulbs** [JDDev0/EnergizedPower#4]
I have made a few more textures that you are free to use in your mod. Changes to the battery textures, energy analyzer, and silicon textures are included.
![battery_8](https://user-images.githubusercontent.com/94999662/219032303-d6315dcf-8e9b-4937-b7c3-7e40348f0f51.png)
![energy_analyzer](https://user-images.githubusercontent.com/94999662/219032304-5c7d34a8-edbe-4d78-8029-3b37ef3aab5e.png)
![silicon](https://user-images.githubusercontent.com/94999662/219032307-ecc0577b-5787-480e-9478-18a82a8182c4.png)
![battery_1](https://user-images.githubusercontent.com/94999662/219032308-dd05b361-f45f-475a-8645-54484dc9baa4.png)
![battery_2](https://user-images.githubusercontent.com/94999662/219032309-9acba1d9-00c7-464c-a0fc-cb1a5ad8db4e.png)
![battery_3](https://user-images.githubusercontent.com/94999662/219032311-b4609850-081d-4004-bc83-8be09ea84f21.png)
![battery_4](https://user-images.githubusercontent.com/94999662/219032312-0f0e3a0f-271e-4b3d-8c02-d8af494417a9.png)
![battery_5](https://user-images.githubusercontent.com/94999662/219032313-0c563d84-670c-4ee3-94f5-8c3b97ff9780.png)
![battery_6](https://user-images.githubusercontent.com/94999662/219032315-fdf64c31-1ffc-4b57-91c6-e3822a4a3192.png)
![battery_7](https://user-images.githubusercontent.com/94999662/219032316-f8f0f138-053c-4344-8111-6dc544b52bad.png)

**Comment by JDDev0** [comment]
Thanks!
