### ISSUE TITLE
[1.21] Energized Power Crashing on Neo Forge

### ISSUE THREAD

**Issue by Periam** [JDDev0/EnergizedPower#42]
After installing the mod, successfully running the game and creating a new work the game crashed.

Minecraft version 1.21
Neo Forge: Neoforge 21.0.14
Mod Version: energizedpower-1.21-2.11.2-neoforge

Crash Log\

[crash-2024-06-17_15.35.19-client.txt](https://github.com/user-attachments/files/15875574/crash-2024-06-17_15.35.19-client.txt)

**Comment by JDDev0** [comment]
There was a breaking change in NeoForge version 21.0.11. I will release a update soon. For now you can use EnergizedPower with NeoForge 21.0.10 or older.

**Comment by JDDev0** [comment]
I have already released the update. You may have to wait a little because of CurseForge verification.
