### ISSUE TITLE
[1.21] Tin ore blocks are dropping tin ore instead of raw tin when mined

### ISSUE THREAD

**Issue by jshipley** [JDDev0/EnergizedPower#43]
I tried mining tin ore with a stone pickaxe and got a tin ore block instead of raw tin. Tin ore should only drop when mined with silk touch.

Jade also showed that tin ore blocks were mineable with shears, which was weird.

Using Energized Power v2.12.0 in Fabric

**Comment by JDDev0** [comment]
I will fix it in the next release.
