### ISSUE TITLE
(Tin Ores) Drop ore blocks if you have an enchanted Pickaxe

### ISSUE THREAD

**Issue by Shadowdane** [JDDev0/EnergizedPower#47]
Minecraft Version: 1.21
Fabric Loader Version: 0.16.0
Energized Power Version: 2.12.1

Both Tin Ores from this mod drop as the block and not Raw Tin if you have any Enchantments on your Pickaxe.   Basically it acts like you have Silk Touch even if the Pickaxe doesn't have Silk Touch.   If I use a Pickaxe with no enchantments it drops a Raw Tin item as expected.

Tried a few different enchanted pickaxes none of them had Silk Touch and all of them just drop the block and not the raw ore.

I tested this standalone with only EnergizedPower and Fabric API installed.
![image](https://github.com/user-attachments/assets/c498b0f2-6d20-4554-851a-7c68f0ce2c96)

![2024-08-20_23 43 58](https://github.com/user-attachments/assets/1cae8901-9c59-4275-98bc-41c3bc45eb99)

**Comment by JDDev0** [comment]
I have fixed it for Minecraft 1.21.1. Almost all mods from 1.21 should be compatible with 1.21.1.

**Comment by Shadowdane** [comment]
Thanks for the update on this.  I guess I'll wait for the next update, my Modpack won't run on 1.21.1 currently has a few required mods which haven't been updated yet to support it.   Just tried to run with 1.21.1 and it isn't compatible right now.

![image](https://github.com/user-attachments/assets/01becc19-ac35-42a5-be02-189f79b0bdfc)
