### ISSUE TITLE
Auto Crafter: Output only slots

### ISSUE THREAD

**Issue by PolostanInsurgency587** [JDDev0/EnergizedPower#5]
A suggestion to add a special slot for output only to the automatic crafting table, this way automatic crafting table could work even if other slots we overfilled with input items making automatiom much easier

**Comment by JDDev0** [comment]
Thanks for your suggestion!

I will set the last 3 slots of the Auto Crafter to be useable for output items only in v1.5.0.
But I'm not yet sure, when I will start working on v1.5.0 or when it will be released.

**Comment by JDDev0** [comment]
This feature will already be released in v1.4.3.

v1.4.3 of Energized Power will be released when JEI and EMI are released for 1.19.4.
