### ISSUE TITLE
Allowing outputs besides sawdust in sawdust slot in sawmill

### ISSUE THREAD

**Issue by TheDarkPreacher** [JDDev0/EnergizedPower#6]
Just like the title says, I would like to be able to have other outputs besides sawdust in the sawmill, like bark from farmer's delight when stripping a log.

Currently using the latest release of the Fabric version and trying to add a recipe with KubeJS to strip logs and leave stripped logs and bark behind.

**Comment by JDDev0** [comment]
Thanks for your suggestion.
I will implement it in v1.4.4.
